### PR TITLE
add registry-mirror / npm-on-ipfs

### PR DESCRIPTION
**Pull request by zeke**

### CODE REVIEW

**Comment by billiegoose** [comment]
Is the "registry-mirror" package deprecated in favor of "ipfs-npm" @diasdavid? And is that the same as "npm-on-ipfs" project?

[registry-mirror](https://www.npmjs.com/package/registry-mirror)
[ipfs-npm](https://www.npmjs.com/package/ipfs-npm)
[npm-on-ipfs](https://github.com/diasdavid/npm-on-ipfs)

**Comment by daviddias** [comment]
@wmhilton `registry-mirror`, the module, will be deprecated once `ipfs-npm` is released. `ipfs-npm` is essentially registry-mirror, but with a name that is easier to identify and with a better CLI for people to use that takes into account all of the feedback received so far. Also, can be good to link more info/explanation of registry-mirror, can be found here - http://blog.daviddias.me/2015/12/08/stellar-module-management

@whyrusleeping is finishing up the unixfs sharding (tl;dr; will enable to store the entire npm on IPFS without having to create a very large MerkleDAG node), once that is done, I'll get back to work on `ipfs-npm` and make it use that feature :)

**Comment by zeke** [comment]
> @whyrusleeping is finishing up the unixfs sharding

Just checking in. How is that process going?

@wmhilton do you want me to revamp this PR, or should I just close it?

**Comment by zeke** [comment]
Also, @diasdavid I'm getting an error when I try to visit http://blog.daviddias.me/2015/12/08/stellar-module-management

screen shot 2016-12-22 at 12 14 47 pm

**Comment by zeke** [comment]
Found it :)

http://blog.daviddias.me/post/stellar-module-management/

**Comment by daviddias** [comment]
Unixfs sharing will be merged on go-ipfs 0.4.6 release (early Q1 2017), meanwhile a lot has been put into `npm-on-ipfs` to make it [faster](https://github.com/diasdavid/npm-on-ipfs/pull/43)

//cc @whyrusleeping

**Comment by billiegoose** [comment]
I'm just going to add links to both registry-mirror and ipfs-npm for now, since it is still transitioning.

**Pull request closed without merging**
